[versions]
kool = "0.19.0"
physx-jni = "2.7.2"

[libraries]
kool-core    = { module = "de.fabmax.kool:kool-core",    version.ref = "kool" }
kool-physics = { module = "de.fabmax.kool:kool-physics", version.ref = "kool" }
physx-jni    = { module = "de.fabmax:physx-jni",         version.ref = "physx-jni" }
